### PR TITLE
Add config site_cookbooks_path

### PR DESCRIPTION
**Pull request by hirocaster**
can chage `site_cookbooks` directory path.

in `.kitchen.yml`
```
  site_cookbooks_path: ./config/site-cookbooks
```

default is under the kitchen root

### CODE REVIEW

**Comment by cheeseplus** [comment]
I don't have any opposition to this one, will get someone else to review.

**Comment by adamleff** [comment]
I'm OK with this concept, but I'd like to see the implementation cleaned up a small bit:

 * `@config` has an attr_reader setup, so let's just call `config` instead of `@config`
 * Many users rely on the `default_config` and `required_config` statements in these classes as the documentation as to what options exist.  Since you are introducing a new option, please add it to `chef_base.rb` with a default value of `nil` so users know it's an available option.

**Comment by cheeseplus** [comment]
I feel like this is covered/superseded by https://github.com/test-kitchen/test-kitchen/pull/393

**Comment by adamleff** [comment]
@cheeseplus I agree and think #393 is the right place to work this out. I'd recommend closing this in favor of #393.

**Pull request closed without merging**
