### PR TITLE
add tests for empty or missing files

### PR DESCRIPTION
**Pull request by miketheman**
No behavioral changes, adds tests for functionality that already seems
to be working correctly.

Closes jamie-ci/jamie#12
Closes jamie-ci/jamie#19

### CODE REVIEW

**Comment by fnichol** [comment]
@miketheman Looks good, but *dang*, Rubocop keeps coredumping on Travis. I'm going to see if rev'ing (finstyle)[https://github.com/fnichol/finstyle] helps by bumping the version of Rubocop.

**Comment by fnichol** [comment]
**Blocked**, pending bump in finstyle. Not fault of this PR but I foresee sadness in Travis

**Comment by miketheman** [comment]
@fnichol bump post #762 .

**Comment by cheeseplus** [comment]
+1

**Comment by miketheman** [comment]
Woot! Finally.

**Comment by adamleff** [comment]
Thanks for the patience, @miketheman. @cheeseplus is working some serious f'ing magic right now.

**Pull request merged**
