### PR TITLE
fix file_manager

### LINKED ISSUE #1337: Unable to download with winrm (undefined local variable or method `session')
## Description

Using the new download feature in #1306 I am unable to download files with winrm

I get this error

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined local variable or method `session' for #<Kitchen::Transport::Winrm::Connection:0x007ffae5aaa658>] on py2-windows-2016
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Which corresponds to this `session` variable here https://github.com/gtmanfred/kitchen-salt/blob/master/lib/kitchen/verifier/runtests.rb#L57

This all works fine with the kitchen-sync/rsync/ssh transport.

## Kitchen Version

I am using the HEAD of the master branch

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
```

## Platform Version

MacOS 10.13.2

## Replication Case

You can replicate it by running `py2-windows-2016` from the `kitchen` branch of https://github.com/gtmanfred/salt

```
bundle install --with vagrant docker --without ec2 opennebula
bundle exec kitchen test py2-windows-2016
```

## Kitchen Output

Here is a gist of all of the output https://gist.github.com/gtmanfred/f88a1eb209b3070fd3cbbf4d3e88afdc

## Kitchen Diagnose

https://gist.github.com/gtmanfred/f88a1eb209b3070fd3cbbf4d3e88afdc#file-diagnose

### PR DESCRIPTION
**Pull request by gtmanfred**
Fixes #1337

Originally implemented here #1306

### CODE REVIEW

**Comment by atheiman** [comment]
Looks like it needs some test changes
Have you verified this manually against a windows box? Im guessing you have one available to try against? I dont but I can probably get one (i think you can get vbox images from Microsoft for testing old IE versions with websites).

**Comment by gtmanfred** [comment]
I have tested our test suite with it, and it is pulling down files correctly now. There doesn't appear to be anything in the winrm transport called `session`

**Comment by atheiman** [comment]
Cool happy it works. But I think youll still want to get the Travis tests passing

**Comment by gtmanfred** [comment]
Thanks @cheeseplus

**Pull request merged**
