### PR TITLE
Busser: improve recursion of files in test suites

### PR DESCRIPTION
**Pull request by L2G**
This should allow directory symlinks to be dereferenced now.

### CODE REVIEW

**Comment by L2G** [comment]
I need to rework this; sorry.

**Comment by coderanger** [comment]
What are the security implications of this? Probably moot since busser runs everything as root anyway, but symlink traversal sets off my security brain, should at least state what the attack surface is.

**Comment by L2G** [comment]
Right now, symlinks to files are already being followed. This change would make it so that symlinks to directories are followed as well. Maybe there could be a security setting for either or both kinds of symlinks.

The idea of symlinked directories came about because right now there doesn't seem to be an easy way to share tests among multiple test suites. The alternatives are copying or symlinking individual test files.

**Comment by coderanger** [comment]
This is a core thing in RSpec (assuming you are using Serverspec), see https://github.com/coderanger/shared-spec-example for an example.

**Comment by L2G** [comment]
Thanks for the tip. I do know how to use RSpec shared examples. In fact, I am trying to leverage that feature a little further. What I am trying to do is use the same shared examples in my Test Kitchen suites and in live checks on remote servers (the latter being run by Serverspec tasks in Rake). Is there a better way to make a common set of shared examples available to all serverspec suites in a Test Kitchen? Is that what the `test/integration/helpers/serverspec` directory is for?

**Comment by coderanger** [comment]
The helpers folder gets copied over for all suites, yes. You can also put your shared tests in a gem, and have Test Kitchen pull them in.

**Pull request closed without merging**
