### PR TITLE
Generate an Ohai hint file for the current driver

### PR DESCRIPTION
**Pull request by schisamo**
This will ensure Ohai loads all cloud-provider specific attribute data during the Chef run.

/cc @test-kitchen/owners

### CODE REVIEW

**Comment by Jimflip** [comment]
would be good to see this in next release so I can remove some ugly code doing the same thing from my cookbook

**Comment by cheeseplus** [comment]
Can we get this rebased or should re repin the issue?

**Comment by palfrey** [comment]
Any news on this? Anything I can do to help?

**Comment by cheeseplus** [comment]
@palfrey this already exists on the drivers themselves, in the case of `kitchen-ec2` so not sure this is something we need any longer. Also, looking at drivers this would hint non-existent things for many.

**Comment by cheeseplus** [comment]
Given the enhancements to Ohai itself, this is no longer even necessary or advised. Closing.

**Pull request closed without merging**
