### PR TITLE
make data_munger more generic

### PR DESCRIPTION
**Pull request by chris-rock**
Simple change to make the data handling more generic

### CODE REVIEW

**Comment by mwrock** [comment]
:+1:

**Comment by chris-rock** [comment]
This requires #956 to be merged first to be green.

**Comment by cheeseplus** [comment]
The above was merged but this needs to be rebased.

**Comment by lamont-granquist** [comment]
seems to be related to #516

**Comment by tas50** [comment]
Lamont rebased this and we're merging it

**Pull request closed without merging**
