### PR TITLE
Added support for Chef 10

### PR DESCRIPTION
**Pull request by acondrat**
I found two things required to support Chef 10:
1. do not pass --force-formatter argument
2. handle :auto log-level

### CODE REVIEW

**Comment by cheeseplus** [comment]
I am really reluctant to merge this on the basis that Chef 10 is woefully unsupported both from a security perspective and also the ruby is so ancient it is also unsupported.

**Comment by acondrat** [comment]
Some people (like me) still have legacy projects to maintain. I'd vote for migrating to chef 12 with my both hands but it's not always easy. According to https://github.com/test-kitchen/test-kitchen/issues/593 - I am not the only one.

**Comment by cheeseplus** [comment]
I totally understand where you're coming from here as I work in the field with customers all the time here but at some point we need to let Chef 10 die and force people to upgrade.

That said, the code seems relatively unobtrusive and shouldn't break anything. I just don't want to spend any of our cycles on Chef 10 issues at this point in time. I'll see what other maintainers say (many of us are at ChefConf now) but thus far most have not been in favor for the reasons outlined above.

**Comment by jjasghar** [comment]
Academically this makes sense, but the pragmatist in me is screaming 👎 on this PR; but that's just me.

**Comment by mwrock** [comment]
I'm :+1: on this. I'm not crazy about supporting older versions, but if users like @acondrat have a need and are willing to submit a PR that is clean and low impact to address that need, then rejoice! I believe this PR fits that bill.

**Comment by cheeseplus** [comment]
After discussion and review, +1 as well

**Pull request merged**
