### PR TITLE
allow command line arguments

### PR DESCRIPTION
**Pull request by mmckinst**
closes issue #917

### CODE REVIEW

**Comment by cheeseplus** [comment]
If you could rebased I'd be happy to get this merged in - that or we'll fix it up as it's a good contribution.

**Comment by mmckinst** [comment]
@cheeseplus I rebased. travis is still failing but appears to be failing on the current master branch already.

**Comment by logicminds** [comment]
@mmckinst hey can you rebase this?  The travis and Gemfile have likely changed causing the build to fail.

**Comment by mmckinst** [comment]
all tests passing now. @cheeseplus can you merge this in?

**Comment by bad-beat** [comment]
Great feature! And at exactly the right time :)

Only found one issue, the double quotes around the powershell code does not work, the script is not executed in my case. Without the double quotes around the script and the arguments works fine.

New to GitHub, should I register a new issue or can this be done under this issue?

**Comment by mmckinst** [comment]
@bad-beat can you post an example what you mean? like post the yaml file without the double quotes that doesn't work and post the one with the double quotes that does work?

**Comment by bad-beat** [comment]
@mmckinst when I have the arguments in my yaml file as shown below. I use the same arguments list for both linux and windows machines.

In bootstrap.sh the arguments are added after the script and they are passed along just fine.
In bootstrap.ps1 the arguments are added after the script, but the whole set of script and arguments are encapsulated by double quotes by this code `code = powershell_shell? ? %{& "#{script}"} : sudo(script)` (from lib/kitchen/provisioner/shell.rb on line 82).
By adding the arguments in my yaml file, the bootstrap.ps1 is no longer executed at all. When I change the shell.rb code so it does not encapsluate the script and arguments in double quotes, the arguments are passed along just fine.

`provisioner:
  name: shell
  privileged: true
  arguments: '-version 01020304'`

**Comment by mmckinst** [comment]
@bad-beat I don't know enough about powershell to debug this. You should create a separate issue for this or submit a PR if your change fixes the problem and won't break anything else.

**Pull request merged**
