### PR TITLE
Use winrm v2 release gems

### PR DESCRIPTION
**Pull request by mwrock**
This is a work in progress and should not be merged until winrm v2 and corresponding releases in winrm-fs and winrm-elevated are released.

This is mostly working but the following needs to happen:
- [x] tighten up error output in winrm (its a bit much)
- [x] convert winrm-elevated and its usage to work with v2
- [x] get the tests passing

### CODE REVIEW

**Comment by mwrock** [comment]
Errors are looking good now. Working to get elevated transport functional.

**Comment by mwrock** [comment]
see https://github.com/WinRb/winrm-elevated/pull/11

**Comment by mwrock** [comment]
Might be changing the shell interface for winrm-elevated

**Comment by mwrock** [comment]
Build break is now filezilla related and I'll address in a separate pr.

**Comment by mwrock** [comment]
This is no longer a work in progress. There are a couple post release items to be done here. Currently the Gemfile pins kitchen-inspec and train to their respective winrm-v2 branches. This breaks the kitchen-init cucumber feature. For now I have commented out that test and after kitchen-inspec and train release we can revert the comments in the kitchen-init test and remove the pins in the gemfile.

**Comment by mwrock** [comment]
If you want to test, this should work with any windows based cookbook. Additionally, kitchen-dsc based projects can also now converge on Windows Nano Server. If you clone https://github.com/mwrock/DSCTextfile and:
```
bundle install
bundle exec kitchen verify
```
that should create my WindowsNanoDCS vagrant box and converge/test the resource.

**Comment by mwrock** [comment]
I should mention here that we have been using this branch in the chef and chef-dk acceptance tests that test every package that drops into the current channel for the past couple months.

**Comment by cheeseplus** [comment]
+ a billion

**Comment by smurawski** [comment]
:+1:

**Pull request merged**
