### PR TITLE
Update platform version defaults in `kitchen init` command.

### PR DESCRIPTION
**Pull request by fnichol**
The updated platforms are:

- ubuntu-14.04
- centos-7.1

References #707
References #663
References chef/chef-dk#382
References chef/chef-dk#378

### CODE REVIEW

**Comment by tyler-ball** [comment]
:+1:

**Comment by tyler-ball** [comment]
Should also note that this depends on https://github.com/test-kitchen/kitchen-vagrant/pull/166

**Comment by jtimberman** [comment]
:cake: :+1:

**Comment by fnichol** [comment]
[kitchen-vagrant 0.18.0](https://github.com/test-kitchen/kitchen-vagrant/releases/tag/v0.18.0) shipped!

**Pull request merged**
