### PR TITLE
Escape paths before running policyfile commands

### PR DESCRIPTION
**Pull request by coderanger**
Some of my coworkers noticed that TK+Policyfiles breaks if there are spaces in some of the enclosing folder names. As the tests say, this comes up with Jenkins a lot, but good hygiene. Notably this is not the full Windows path escape function because [it is huge and annoying](https://github.com/poise/poise/blob/master/lib/poise/utils/win32.rb#L65-L101) and I think this should cover all non-what-were-you-thinking cases.

### CODE REVIEW

**Comment by johnbellone** [comment]
🎸

**Comment by mwrock** [comment]
:+1:

**Comment by mwrock** [comment]
Needs a rebase

**Comment by coderanger** [comment]
Boo rebase yay merge commits ;-)

**Pull request merged**
