### PR TITLE
Fixes Chef Client installation on Windows Guests

### LINKED ISSUE #601: PR#589 Causes chef-client installations to report as failed when they have actually succeeded
#589 seems to be causing my converges to fail. I'm using bundler to pull in the latest github code for test-kitchen (windows-guest-support branch) & kitchen-ec2 (afiune/kitchen-ec2 Transport branch) and running 'bundle exec kitchen create' is launching an ec2 instance successfully, however when running the converge, it fails on trying to install chef-client. It makes no difference installing the latest omnibus or specifying an 11.x version.

Logging into the Win2012 server shows that Chef Client is in fact installed correctly.

```
-----> Installing Chef Omnibus (latest)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Transport WinRM exited (1) using shell [powershell] for command: [
# @return True if chef path exist, False otherwise
function is_chef_installed { Test-Path /opscode/chef }

# @param $version the requested version of omnibus package
# @return True if omnibus needs to be installed, False otherwise
function should_update_chef($version) {
  if (-Not (is_chef_installed)) { return $true }

  try {
    $chef_version=(chef-solo -v).split(' ',2)[1]
  } catch [Exception] {
    $chef_version = ''
  }

  switch ($version) {
    { 'true', $chef_version -contains $_ } { return $false }
    'latest' { return $true }
    default { return $true }
  }
}

# @param $chef_url The url where we will download chef
# @param $chef_msi Temporal MSI path
function download_chef($chef_url, $chef_msi) {
  Write-Host -NoNewline "`r`tDownloading Chef..."
  (New-Object System.Net.WebClient).DownloadFile($chef_url, $chef_msi)
  Write-Host -NoNewline "`r`tDone!              "
}

# function to install chef with sort of a nice progress bar
function install_chef {
  $proc_msi = Start-Process -FilePath 'msiexec.exe' -ArgumentList "/qn /i $chef_msi" -Passthru
  $bar = ""
  while (-Not $proc_msi.HasExited ) {
    Write-Host -NoNewline "`r`t[MSI] [$bar"
    Start-Sleep 2
    $bar += "#"
  }

  if ($proc_msi.ExitCode -ne 0) {
    throw "msiexec was not successful. Received exit code $($proc_msi.ExitCode)"
  }
  rm -r $chef_msi
  Write-Host -NoNewline "`r`t[MSI] [$bar] Completed!
"
}

  $chef_msi = $env:systemdrive + "\chef.msi"

  If (should_update_chef latest) {
    Write-Host "-----> Installing Chef Omnibus (latest)
"
    download_chef "http://www.chef.io/chef/install.msi?" $chef_msi
    install_chef
  } else {
    Write-Host "-----> Chef Omnibus installation detected (latest)
"
  }
]
REMOTE ERROR:
msiexec was not successful. Received exit code 
At line:42 char:5
+     throw "msiexec was not successful. Received exit code 
$($proc_msi.ExitCode)"
```
It would appear as though Powershell is not actually returning anything in $proc_msi.ExitCode

I'm not a windows developer, but I thought that powershell could not be relied on to return an exit code under all circumstances ?

### PR DESCRIPTION
**Pull request by robcoward**
Fixes #601 - It removes the progress bar as the MSI installs due to calling Start-Process with the -Wait option, but keeps the check on the Exitcode.

cc @afiune @jdmundrawala

### CODE REVIEW

**Comment by jdmundrawala** [comment]
But I love @afiune's progress bar

**Comment by afiune** [comment]
I love it too.. :disappointed_relieved: I rather prefer it than the `Exitcode` haa :smile:

**Comment by jdmundrawala** [comment]
I wouldn't go that far. I would rather figure out why ExitCode is broken, and then why you #'s are not being flushed

**Comment by afiune** [comment]
I was just kidding.. :smile: We definitely need to found the root cause!

**Comment by tyler-ball** [comment]
I don't know enough about PowerShell to know the right course of action - although if this PR works I would rather merge it and fix an issue, then address the download bars in another bug.

@jdmundrawala does this get a :+1: from you?

**Comment by jdmundrawala** [comment]
sorry @afiune :disappointed: :+1:

**Comment by afiune** [comment]
@tyler-ball @jdmundrawala I am not against this at all. I like the Exitcode validation. :smile: 

The only reason I put that pretty bar (lol) is because if you have very low bandwidth you will wait a lot to pull down chef without knowing you are actually downloading it. Also in big enterprises there are proxy issues and if that happen you can stay there waiting for hours, without knowing (again) if it is working or not. 

If we merge this I would expect a squash of the five commits to only one with a good message ... :smile_cat:

**Comment by robcoward** [comment]
Have had my first experiments with git rebase and removed the unnecessary commits and reverts. Have raise new pull request #615 with a single commit.

**Comment by jdmundrawala** [comment]
You should generally just force push to your feature branch, no need for a new PR

**Pull request closed without merging**
