### PR TITLE
make rubocop glücklich

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by mwrock** [comment]
:+1:  yes! glücklich !!

**Comment by cheeseplus** [comment]
+1

**Comment by chris-rock** [comment]
This fixes style issues introduced in https://github.com/test-kitchen/test-kitchen/commit/31b34d40f003c20b5bfbfd38b4828ab3c210fc13#diff-52c976fc38ed2b4e3b1192f8a8e24cffR69

**Comment by chris-rock** [comment]
cc @jkeiser

**Comment by adamleff** [comment]
This changes "Exclude From Changelog" and "Upstream Bug" being 2 excluded labels to 5 labels excluded named "Exclude", "From", "Changelog", "Upstream" and "Bug", which I don't think is intended. 

We probably cannot use the %w decorator here and should just use `[]`.

**Comment by chris-rock** [comment]
@adamleff you're right, great catch. Instead of changing the %w decorator I filtered all label names that are not available in tk

**Comment by adamleff** [comment]
:+1:

**Comment by thommay** [comment]
:+1:

**Pull request merged**
