### PR TITLE
using preferred config name for list output

### LINKED ISSUE #1423: Missing config errors point to the old preferred config name
If you try to run `kitchen list` in a directory without a kitchen.yml file you get an error message that mentions it can't find the .kitchen.yml file not the kitchen.yml file. We should point users to the new preferred location.

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Kitchen YAML file /Users/tsmith/dev/work/chef/.kitchen.yml does not exist.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

### PR DESCRIPTION
**Pull request by tarcinil**
when config_file doesn't exist, say that kitchen_yml doesn't exist, adding test to check for raised exception when read is used without a config file existing

fixes #1423

### CODE REVIEW

**Comment by coderanger** [comment]
So the problem here is that this will give incorrect information in cases where the default config location has been changed. What we should probably do is change `default_config_file` to return `kitchen_yml` if neither are present.

**Comment by tarcinil** [comment]
@coderanger 

I have changed the method for `#default_config_file` so that it is returning `#kitchen_yml` when neither file exists.

The change seems to anger the existing tests. 

```
  1) Error:
Kitchen::Loader::YAML::.initialize#test_0002_when kitchen.yml not present, falls back to .kitchen.yml:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/vburton/Code/test-kitchen/spec/kitchen/loader/yaml_spec.rb:57:in `block (3 levels) in <top (required)>'

  2) Error:
Kitchen::Loader::YAML::.initialize#test_0007_sets local_config based on Dir.pwd by default:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/vburton/Code/test-kitchen/spec/kitchen/loader/yaml_spec.rb:96:in `block (3 levels) in <top (required)>'
```

I am going to review the test errors tomorrow and added WIP to the title.

**Comment by coderanger** [comment]
Yeah, I would totally believe the tests are a bit overly brittle right now :)

**Comment by tarcinil** [comment]
Seems interesting.  When using #kitchen_yml as the return, #diagnose return nil and causes those tests to fail.  

I have some ideas, but I’ve been busy.

**Comment by tarcinil** [comment]
Closed and re-opened PR to re-trigger build due to Travis CI issues.

**Comment by tarcinil** [comment]
@coderanger 
This is ready for review.

**Comment by tas50** [comment]
I just recreated a pretty similar fix locally. This one is already open though. Thanks for taking this on. It will avoid some user confusion in the future.

**Pull request merged**
