### PR TITLE
Add retry support for WinRM

### PR DESCRIPTION
**Pull request by bdwyertech**
Currently, while provisioning a new Windows instance and the `PING_COMMAND` fails, Kitchen errors out and deletes the instance, ignoring retry logic.  

I have found that sometimes you'll get a 500 from WinRM when it first fires up, so the first pass of `wait_until_ready` will error out instead of retrying.

Windows AMI's can take a few minutes to spin up, so this can be a pretty big time waste.

#### Typical Scenario:
```shell
     Waited 365/3000s for instance <i-0ffffffffffffff> to become ready.
       Waited 370/3000s for instance <i-0ffffffffffffff> to become ready.
       Waited 375/3000s for instance <i-0ffffffffffffff> to become ready.
       Waited 380/3000s for instance <i-0ffffffffffffff> to become ready.
       Waited 0/3000s for instance <i-0ffffffffffffff> to fetch windows admin password.
       Retrieved Windows password for instance <i-0ffffffffffffff>.
       EC2 instance <i-0ffffffffffffff> ready (hostname: 10.255.255.255).
       [WinRM] Established
       
       Removing automatic key pair kitchen-defaultWindows2016-gitlabrunner-ip10255255255bfsabc123-2018-10-17T17:33:50Z-h0qawz7k
-----> Destroying <default-Windows-2016>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [Connection refused - Connection refused - connect(2) for "10.1.23.45" port 5985 (10.1.23.45:5985)] on default-Windows-2016
```

### CODE REVIEW

**Comment by cheeseplus** [comment]
This seems sane and safe, can't say I've ever seen that error with Windows EC2 instances but it seems more than plausible.

**Comment by chefbob** [comment]
We’ve had this problem.

**Comment by bdwyertech** [comment]
Alright, looks like the `wait_for_ready` needs a retry too... Got a different error today when using WinRM over HTTPS

**Comment by cheeseplus** [comment]
Perhaps https://github.com/test-kitchen/test-kitchen/pull/1493 and https://github.com/test-kitchen/test-kitchen/issues/1331#issuecomment-435736827 are related?

**Comment by dwoz** [comment]
@cheeseplus This issue is addressing a connection refused error from WinRM

```
Failed to complete #destroy action: [Connection refused
```

 #1331 is a timeout error from WinRM

```
Failed to complete #converge action: [execution expired] 
```

**Comment by bdwyertech** [comment]
That’s correct.

Moving the retry to the wait for ready block seems to have eliminated this issue.  I’ll let it marinate for a few more days and then push an update here.

**Comment by tyler-ball** [comment]
Thanks for the PR @bdwyertech! I wasn't exactly able to repro but thanks for testing and baking on your side some. The changes make sense to me. I'm going to push another commit to make those retries configurable based on the existing 'retry' settings, and add a test for this. Cheers!

**Comment by bdwyertech** [comment]
@tyler-ball Any chance we could get a gem release cut before the next ChefDK rolls out?

#1496 and #1493 seem like they'd make the WinRM support a bit more robust too.

**Pull request merged**
