### PR TITLE
first try for an issue template

### PR DESCRIPTION
**Pull request by smurawski**
@test-kitchen/core Thoughts? Additions? Subtractions?

### CODE REVIEW

**Comment by mwrock** [comment]
:+1:

**Comment by tas50** [comment]
:+1:

**Comment by sethvargo** [comment]
This looks good to me @smurawski, but can we dump these in the `.github` directory instead of putting it at the top-level?

Here is what we do for Vagrant. I find it helpful to show people how to use GHFM too, since otherwise they just dump debug logs all over the place: https://raw.githubusercontent.com/mitchellh/vagrant/master/.github/ISSUE_TEMPLATE.md

**Comment by smurawski** [comment]
@sethvargo thanks.. I'll make some of those tweaks!

**Comment by sethvargo** [comment]
LGTM

**Pull request merged**
