### PR TITLE
Release 1.18

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Any chance you could add #1252.  As is the enforce_idempotency option fails every time.

**Comment by tas50** [comment]
@MarkGibbons waiting on a green build for that PR

**Comment by MarkGibbons** [comment]
Sorry, #1252 isn't my pull request and I don't know how to do anything with it.  I put in a new PR, #1282, that should replace #1252.

**Comment by cheeseplus** [comment]
We want to fix the net-ssh kerfuffle in this release so we'll want to update the release notes for the PRs that have been merged, including #1252

**Comment by cheeseplus** [comment]
Closing in favor of #1287 and I need thumbs over there plzkthx

**Pull request closed without merging**
