### PR TITLE
I nominate Seth as lieutenant of Test Kitchen

### PR DESCRIPTION
**Pull request by tyler-ball**
I've recently become LT of Chef Provisioning and won't be able to effectively perform my duties of both.  But I nominate Seth because he has done an awesome job so far!

### CODE REVIEW

**Comment by iennae** [comment]
:+1:  Seth is fantastic. Really appreciate his leadership :D

**Comment by mwrock** [comment]
:+1:

**Comment by adamleff** [comment]
Never have I wanted to mash the big green button more. :+1:

**Comment by robbkidd** [comment]
:heavy_plus_sign::100: 

:raised_hands: :skull: :octopus:

**Comment by luckymike** [comment]
Gonna be sooooo awkward when @cheeseplus sees this as no one mentioned him in the thread... 😁

**Comment by drrk** [comment]
:+1: (Not sure if I get a vote or not thought :smile:)

**Pull request merged**
