### PR TITLE
Move Shell provisioner data to provisioner as well

### PR DESCRIPTION
**Pull request by paracycle**
Each test suite should be able to specify its own `script` and
`data_path` if the provisioner in use is the Shell provisioner.

### CODE REVIEW

**Comment by cheeseplus** [comment]
Could this be rebased? We're planning on moving Chef out of core like other provisioners so this lines u well either way.

**Comment by paracycle** [comment]
That's great news. I did a quick mechanical rebase of the original commit but didn't have time to check if anything else needs updating in the new code as well. Please let me know how you want to proceed.

**Comment by cheeseplus** [comment]
I kicked the build to see if this will work but we will need it rebased again to get it in but I'd still love to see this in.

**Comment by paracycle** [comment]
@cheeseplus I rebased the commit on the latest master, however, it seems there is a problem with `nio4r` dependency on build systems and that seems to be failing (some of the) test runs.

**Pull request closed without merging**
