### PR TITLE
Fix the Azure Pipelines Build

### PR DESCRIPTION
**Pull request by smurawski**
Initial Linux builds were failing due to a higher level environment variable influencing a cucumber tests (the KITCHEN_YAML that was set in the build matrix).  I've broken out the tests a bit more and just apply the environment variable to the step where it is needed.

### CODE REVIEW

**Comment by tyler-ball** [comment]
@smurawski Running into these same failures in https://github.com/test-kitchen/test-kitchen/pull/1573 - I was able to figure out the `chmod +x` part but no idea about the Aruba failures. Any guesses as to what is going on?

**Comment by smurawski** [comment]
@tyler-ball yeah, still trying to sort out why one of the cucumber tests is failing. :/  hopefully, I'll have it sorted out shortly. I'm going to close this PR as I'm making a few changes in another azure devops instance tied to my fork (forgot this branch had a live PR.

**Comment by smurawski** [comment]
Never mind - I just sorted it out.  Fix inbound shortly.  (higher level environment variable was throwning things off)

**Comment by smurawski** [comment]
@tyler-ball @stuartpreston  @tas50 Sorted out my mistake.  I'm not sure why it worked for me last week when I opened the initial PR, but it's building properly now.

**Pull request merged**
