### PR TITLE
Check the exit code of msiexec

### PR DESCRIPTION
**Pull request by jdmundrawala**
cc @fnichol @btm @mwrock @tyler-ball @afiune @mattstratton @cmluciano

### CODE REVIEW

**Comment by tyler-ball** [comment]
I am totally unfamiliar with powershell, but it looks right, so.... :+1:

**Comment by mwrock** [comment]
Looks good to me.

**Comment by sethvargo** [comment]
@jdmundrawala who do you want on this team and what do you want it to be called?

**Comment by jdmundrawala** [comment]
@sethvargo tk-windows would be good and yes please.
Thanks!

**Comment by fnichol** [comment]
LGTM and gang-reviewed, right now!

**Comment by sethvargo** [comment]
@jdmundrawala you have @test-kitchen/windows now. Some folks need to accept their invites though.

**Comment by jdmundrawala** [comment]
Awesome!

**Pull request merged**
