### PR TITLE
Enable Rubocop

### PR DESCRIPTION
**Pull request by Xorima**
# Description

- Enables consistent styling throughout the project.
- Starts using rubocop for styling on all pull requests. 

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by Xorima** [comment]
@tas50 what are your thoughts on this before I continue fixing the last 200+ errors still in existence.

**Comment by tas50** [comment]
We probably want to enforce chefstyle here so we don't have a moving target. At one point we used RuboCop in a lot of the kitchen projects and the end result was failed builds for style every time someone opened a PR. It was a real hassle to have to work with contributors to fix unrelated issues before we could move forward with the actual PRs.

**Comment by Xorima** [comment]
Sounds good to me, I was going to use a tweak of cookstyle bot to auto run remediation, happy for it to be chef style though

**Comment by tas50** [comment]
Closing this PR out. If you want to do it with Chefstyle let's get a new PR

**Pull request closed without merging**
