### PR TITLE
Add missing parameter "data" to method def and call

### PR DESCRIPTION
**Pull request by AntonOfTheWoods**
The variable data is referred to but out of scope, adding as a
parameter.

### CODE REVIEW

**Comment by DPD-30** [comment]
I just submitted pr 1252 with the exact same change.  You beat me to it Nice work.  Now to get one of them merged.

**Comment by AntonOfTheWoods** [comment]
<rant> Yep, the problem is that the wonderfully complete and super tests don't work. I must confess the whole Chef (ruby?) ecosystem seems to have this really pleasing tendency of having tests work for about 3 days and then stop working, so when you want to fix really basic bugs you are subjected to 4 hours of fixing rubbish that has nothing to do with your fix...</rant> I am super busy until middle of next week but will try and put aside some time I would have spent relaxing to fix this.

**Comment by coderanger** [comment]
@AntonOfTheWoods Test Kitchen is maintained entirely through volunteer effort and most of that has been going to docs and triage lately. We welcome any help in improving maintenance.

**Comment by gordonbondon** [comment]
Looks like checks here were failing not because of changes made in this PR. Tests were fixed since then. 
Can build be restarted? It would be really nice to have this fix merged and released.

**Comment by MarkGibbons** [comment]
This was fixed by #1282

**Pull request closed without merging**
