### PR TITLE
Replace sudo -E

### LINKED ISSUE #307: Use of sudo -E breaks compatibility with CentOS 5
the version of sudo in CentOS 5 does not support the -E (preserve environment) flag, so omnibus installation fails.

ref: https://gist.github.com/nathwill/8137556

### PR DESCRIPTION
**Pull request by aaron-lane**
This fixes #307; any other changes are intended to be refactors to improve readability and reduce complexity.

`sudo su -m` was chosen to maintain compatibility with the current usage of `sudo -E`.

### CODE REVIEW

**Comment by jtimberman** [comment]
Is `su -m` portable to all Linux/Unix-like platforms?

**Comment by aaron-lane** [comment]
As far as I have seen, but other platform jockeys can certainly weigh in. I know the initial suggestion was to clear the environment with ```su -l```, but some of the scripts that TK generates assume access to the nonroot environment and I didn't want to go that far in changing behavior.

**Comment by MarkGibbons** [comment]
I don't see the sudo -m option in the source at http://www.sudo.ws or in the man page http://www.sudo.ws/sudo/man/1.8.11/sudo.man.html.  The versions of sudo I have on rhel 5, rhel 6 and solaris doesn't support a -m option.

**Comment by aaron-lane** [comment]
@MarkGibbons: The original command used was ```sudo -E```, but the change is to ```sudo su -m -c```, which should function in the same manner.

**Comment by robcoward** [comment]
-1 - Not sure what you are trying to achieve, but -m -c don't appear to be valid options with the version of sudo shipped with CentOS6.5

**Comment by aaron-lane** [comment]
@robcoward: Again, these are not sudo options; the full command is ```sudo su -m -c```.

**Comment by martinisoft** [comment]
:+1: from FreeBSD land. I can confirm FreeBSD at least version 9.3-RELEASE and newer has support for those options in su. See https://www.freebsd.org/cgi/man.cgi?query=su&apropos=0&sektion=0&manpath=FreeBSD+10.1-RELEASE&arch=default&format=html

**Comment by fnichol** [comment]
After talking this one over, I think we have an alternate solution that still leaves things configurable and maximally portable:

How about adding `:sudo_command` configurable option to Provisioner::Base (and Busser) that defaults to `"sudo -E"` which lets you override it at any level (all instances, a specific platform, etc.)?

Is this something you'd like to tackle or should we add an issue for tracking?

**Comment by aaron-lane** [comment]
Sorry, I was offline for a few days.

I can definitely take a crack at implementing your idea.

**Pull request closed without merging**
