### PR TITLE
Pass in all local env vars to the instance

### LINKED ISSUE #1622: Feature - Enable pushing in Environment variables
## Description

Currently the contents of the `CI` environment variable is pushed into the created virtual machine from the host, while this works well it is limiting in terms of what you can push in

I would like to propose that any environment variables that start with `KITCHEN_` is pushed into the created VM the same way the `CI` environment variable is today, but with the `KITCHEN_` stripped off, this would make handling the chef license easy for example, `KITCHEN_CHEF_LICENSE=accept` becomes `CHEF_LICENSE=accept` without having to update every kitchen file.

### PR DESCRIPTION
**Pull request by Xorima**
## Description

This commit will add the ability to push in additional env vars from the host to the client, it will push all env vars which start KITCHEN_ to the machine

Signed-off-by: Jason Field <jason@avon-lea.co.uk>

## Issues fixed

#1622

### CODE REVIEW

**Comment by lamont-granquist** [comment]
You can't use that as the prefix, there's already variables like `KITCHEN_YAML` which occupy that namespace, at a minimum that is confusing, and the side effect of having those variables all injected into the virt may cause problems in the future.

It needs to be relatively clear from the prefix that they are env vars which are being deliberately injected into the client, just from the name, in order to reduce confusion.

**Comment by Xorima** [comment]
Hey,

Thanks for the feedback, totally forgot about those ones. 

Do you have any opinions on what the prefix should be @lamont-granquist, I personally am just after the feature so I can push in the `chef_license` env var (it is not pushed currently) and some very odd proxy settings, but also it may be more flexible than the current `ci` push. 

Some of my initial thoughts, 

- `kitchen_envpush` - this is at least very clean, but it is also very long named?
- `tk_vmvar` - this uses a different namespace and says it's a vm variable, but is that really clear enough?
-`ci_` - we already push in the `ci` env var so this would be similar behaviour (except we would be removing the `ci_` prefix) however the behaviour still not clear from the name

**Comment by Xorima** [comment]
Make it `tk_` - tim

**Comment by lamont-granquist** [comment]
`TKENV_FOO` maybe?

doesn't collide, has "env" in it, has "tk" in it, but isn't obnoxiously long to type.

**Comment by Xorima** [comment]
done @lamont-granquist

**Comment by Xorima** [comment]
Where should I doc these new features @tas50 ?

**Pull request merged**
