### PR TITLE
Adding Maintainers file

### PR DESCRIPTION
**Pull request by cheeseplus**
As per Rally discussions - adding new fleet of maintainers.

### CODE REVIEW

**Comment by mwrock** [comment]
:+1:

**Comment by smurawski** [comment]
:+1:

**Comment by adamleff** [comment]
With a growing maintainers list, obtaining a "simple majority" may be time-consuming... we may want to reconsider that at some point.  :+1: regardless :)

**Comment by mwrock** [comment]
Or do we go with the rule of 2 +1s. I think that's preferable.

**Comment by adamleff** [comment]
That would be my preference as well. Even though it's not an "official Chef project," such a policy would put it more in line with RFC 030. We could even state here that we're following that model.

**Comment by cheeseplus** [comment]
To be clear I was cargo culting RFC30 as the skeleton so I'm happy to acknowledge the influence - just wanted to make clear the non-official support. Suggestions for text/PR?

**Comment by adamleff** [comment]
When RFC030 was accepted, we did not go back and modify many of the MAINTAINERS.md files in our projects, so they're kind of in conflict. :smile: 

Proposed:

```
This file lists how the Test Kitchen project is maintained. When making changes
to the system, this file tells you who needs to review your patch. You need at least
2 :+1: votes from the users listed below. Additionally, you need to not receive a veto
from the Lieutenant or the Project Lead.
```

**Comment by cheeseplus** [comment]
Done

**Comment by adamleff** [comment]
:rocket: :cake: :100:

**Comment by smurawski** [comment]
:+1:

**Pull request merged**
