### PR TITLE
Support specifying exact nightly/build

### PR DESCRIPTION
**Pull request by jaym**
We need to url escape versions
Feels like something install.sh should do, but it does not.

This is step 3:
cc @fnichol @mcquin

### CODE REVIEW

**Comment by jaym** [comment]
The test failures seem unrelated. I get them on master when I run locally as well

**Comment by mcquin** [comment]
:+1:

**Comment by smurawski** [comment]
:+1:  Test failure looks unrelated.

**Comment by tyler-ball** [comment]
:+1:

Let me know if you need help with the Travis build

**Pull request merged**
