### PR TITLE
Check the actual value, because `password: nil` shouldn't disable sending the key.

### PR DESCRIPTION
**Pull request by coderanger**
This is currently breaking kitchen-docker.

### CODE REVIEW

**Comment by coderanger** [comment]
More specifically this breaks everything still using `SSHBase` because of `SSHBase#backcompat_merged_state` which always sets the password to nil.

/cc @mwrock This should be considered a high-prio issue with 1.11 I think.

**Comment by mwrock** [comment]
oy vey :+1:

**Comment by coderanger** [comment]
Going to use this an excuse to de-legacy kitchen-docker but other drivers might be sad too.

**Comment by mwrock** [comment]
I'll aim to get a 1.11.1 release out this weekend and make sure next week's dk has it.

The one redeeming point of all of this is having a 1.11.1 version number.

**Pull request merged**
