### PR TITLE
Improve support for powershell on Windows by wrapping commands and forcing binary paths

### PR DESCRIPTION
**Pull request by gh2k**
Tested using ssh and winrm transports (using vagrant_winrm driver as I couldn't get winrm transport to work) for both bourne and powershell shells. Both work fine on my setup and Linux builds appear to be unaffected.

### CODE REVIEW

**Comment by gh2k** [comment]
I'm surprised that you had issues with paths, as this explicitly calls the busser binstub with the full path to the Ruby interpreter.

I /did/ have to make sure I specified the relevant paths in my .kitchen.yml, and I'm using windows_chef_zero as my provisioner.

```
  - name: windows-2008-r2
    run_list:
    - recipe[windows::default]
    driver:
      name: vagrant_winrm
      box: widgit_win2k8r2 # proprietary
    provisioner:
      name: windows_chef_zero
      root_path: c:/windows/temp/kitchen
      ruby_bindir: c:/opscode/chef/embedded/bin
    transport:
      shell: powershell
      sudo: false
    busser:
      ruby_bindir: c:/opscode/chef/embedded/bin
      root_path: c:/tmp/busser
```
It would be nice if busser could somehow know that it's targeting Windows and update the default values for its paths to be Windowsy.

I did run into the issues you described re: kitchen, but running it under bundler seemed to fix that for me. I'll take another look at native winrm transport to see if I can get it working.

**Comment by mwrock** [comment]
BTW: I have evolved my PR #562 to add a `shell` abstraction for constructing win vs. linux commands and the correct one should be chosen based on the transport. That way you dont need t oembellish the `.kitchen.yml` with the windows paths.

**Comment by gh2k** [comment]
Sounds like I should be trying your PR to see if any of this is still necessary.

**Comment by gh2k** [comment]
Incidentally, the issue I end up with on native-winrm vs. vagrant-winrm on this branch is that PATH is getting mangled with a windows-style path in it. Whenever one of the tests runs `sh` Bad Things start happening due to semicolons and instances of `c:`. I haven't yet been able to diagnose why.

**Comment by gh2k** [comment]
I can confirm that I have this working using winrm transport via your PR #562 and jdmundrawala/kitchen-vagrant@246bfde

The Transport branch of afiune/kitchen-vagrant didn't appear to work on its own, as things blew up when attempting to upload the test suite (I presume):
````
-----> Verifying <default-windows-2008-r2>...
       Suite path directory /tmp/busser/suites does not exist, skipping.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #verify action: [Bad HTTP response returned from server (500).]
>>>>>> ----------------------
````

Closing this. It appears the problems have been solved more thoroughly elsewhere. Also, I need only specify the vagrant box and transport name in my kitchen.yml with that setup. Much improved.

**Comment by mwrock** [comment]
Just curious: do you see the PATH problem on PR #562 as well?

**Pull request closed without merging**
