### PR TITLE
Add synced_folders feature support

### PR DESCRIPTION
**Pull request by aogail**
Per the discussion on test-kitchen/kitchen-ec2#240, I'm opening a
PR to provide support for a basic "synced folders" feature in the
base test kitchen driver.

The `Kitchen::Driver::Base` class now has a `synced_folders` config
option and a `sync_folders()` method that driver implementations
may use to support basic folder syncing.

This is meant to be similar to the kitchen-vagrant synced_folders
feature: you specify a local path and a remote path, and kitchen
will copy the local path to the remote path on the VM.

Driver implementations may utilize this basic infrastructure to
support the `synced_folders` config or may still implement it
themselves, like kitchen-vagrant does. Assuming this change
is accepted I'll update kitchen-ec2 to utilize it.

### CODE REVIEW

**Comment by aogail** [comment]
It appears that the Ruby 2.2.4 "proxy tests" build ran without AWS credentials set, and thus failed. Let me know if there is something I need to do to make that work. =)

**Comment by mwrock** [comment]
:+1: the AWS travis failure is fine and expected on outside repos.

**Comment by mwrock** [comment]
@aogail now that we have merged #980 travis "should" go green if you rebase this.

Also, it would be awesome if you added the use of this into the built in [proxy driver's](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/driver/proxy.rb) create method and added a verify test that the the sync worked.

**Comment by aogail** [comment]
@mwrock Cool, thanks. I'll take a look at the proxy driver and give it a shot.

**Comment by sclarson** [comment]
@aogail Any further progress on this?  If time is an issue I'd help with it.

**Comment by aogail** [comment]
@sclarson Help would be great, I haven't done anything more on this as I got distracted by other projects.

**Comment by sclarson** [comment]
@mwrock I'm looking at the [proxy driver](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/driver/proxy.rb#L35) and that inherits from [sshbase](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/driver/ssh_base.rb#L43) which is deprecated.  Should the functionality be added into [sshbase](https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/driver/ssh_base.rb#L43) for now?

**Comment by cheeseplus** [comment]
Closing this one due to age and conflicts.

**Pull request closed without merging**
