### PR TITLE
Allow custom sudo path. Also redact the password in the ssh opts

### PR DESCRIPTION
**Pull request by scotthain**
:construction: 

@fnichol - this is a possible way to do this, I'm totally open to other suggestions.

### CODE REVIEW

**Comment by btm** [comment]
Does this replace https://github.com/test-kitchen/test-kitchen/pull/592 ?

**Comment by scotthain** [comment]
@btm it could actually - I didn't remove the -E flag as located here: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/shell_out.rb#L59 but I could update to default to 'sudo -E' and allow for what is in #592.

**Comment by scotthain** [comment]
@btm I think I've added all the things that #592 was looking to do. @aaron-lane didn't mean to steal your thunder! does this work for you as well?

**Comment by aaron-lane** [comment]
@scotthain One of the raised issues was that `-E` is not supported on all platform implementations of sudo, so I'm not sure if this covers all of the original concerns.

**Comment by scotthain** [comment]
@aaron-lane this defaults to 'sudo -E', but will allow you to provide (in .kitchen.yml) a different executable, be it 'sudo su -m -c' or '/my/custom/path/sudo'

That being said, there is a bug in this PR which I am fixing right now regarding busser.

**Comment by aaron-lane** [comment]
@scotthain I'm guilty of not reading thoroughly :sad:. This sounds like an excellent solution!

**Comment by scotthain** [comment]
@aaron-lane no worries! I'll try and have this updated a fixed fully either today or tomorrow. - Ran into some oddities with busser, as one does.

**Pull request closed without merging**
