### PR TITLE
Exit the execute loop once the exit code is found.

### PR DESCRIPTION
**Pull request by coderanger**
This matters when multiple, parallel operations are using the same session.

### CODE REVIEW

**Comment by coderanger** [comment]
This is a duplicate of #453. I forgot I already submitted this last year.

**Comment by metadave** [comment]
Should this issue be closed in favor of #453, as that PR passes Travis?

**Comment by coderanger** [comment]
I'm sure those only passed because they ran a year ago and somewhere in there things in the test harness were broken. It looks like the test system doesn't correctly wait for the Net::SSH connection to close.

**Comment by metadave** [comment]
yes, my bad, I should have rerun the tests. I'll ask folks internally how
to resolve the issue.

Cheers -
Dave

On Tue, Jun 2, 2015 at 5:51 PM, Noah Kantrowitz <notifications@github.com>
wrote:

> I'm sure those only passed because they ran a year ago and somewhere in
> there things in the test harness were broken. It looks like the test system
> doesn't correctly wait for the Net::SSH connection to close.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/test-kitchen/test-kitchen/pull/724#issuecomment-108109350>
> .
>



-- 

*Dave Parfitt* — Engineering

716.218.3213– dparfitt@chef.io - my: Linkedin
<http://www.linkedin.com/in/metadave/> Twitter
<http://www.twitter.com/metadave>

*CHEF*

TM

*chef.io* <http://www.chef.io/> Blog <http://www.opscode.com/blog/> Facebook
<https://www.facebook.com/getchefdotcom> Twitter <https://twitter.com/chef>
Youtube <https://www.youtube.com/getchef>

**Comment by lamont-granquist** [comment]
paging @coderanger -- merge or close?

**Comment by coderanger** [comment]
Still needed AFAIK but it was causing text failures. Should get rebased at least and run through travis.

**Pull request closed without merging**
