### PR TITLE
Fix appveyor builds

### PR DESCRIPTION
**Pull request by smurawski**

### CODE REVIEW

**Comment by mwrock** [comment]
sheesh. I wonder if its `pry-stackexplorer` thats the culprit here?

**Comment by mwrock** [comment]
lets just blame it all on WMF5

**Comment by smurawski** [comment]
https://github.com/brigade/overcommit/issues/387  Now we are back to failing on the test-kitchen run failing to find the mercurial bits to download and install.

**Comment by mwrock** [comment]
:+1: good old filezilla

**Comment by smurawski** [comment]
Had to find something that was easy to install that wasn't on an appveyor box :)

**Pull request merged**
