### PR TITLE
Use latest mixlib-install 1.0.2

### PR DESCRIPTION
**Pull request by mwrock**
~~This is currently blocked on a release of current mixlib-install master.~~

Prinary motivation for this is to use released TK to run acceptance tests in chef and chef-dk to help validate that the released version of test-kitchen works.

cc @sersut

### CODE REVIEW

**Comment by sersut** [comment]
Thanks for taking a stab at this @mwrock. To share my context about this change first:

When not using mixlib-install, test-kitchen creates a script that downloads `install.sh` from omnitruck and runs it. With mixlib-install however test-kitchen now has the contents of the scripts to run. In my previous work I found that we need to first render the contents of the script on the remote machine and set the `install_command` to run the rendered script in order to support all the current parameters of test-kitchen including `sudo`. 

That was why in https://github.com/sersut/test-kitchen/pull/1 there is some dance in `lib/kitchen/provisioner/base.rb` to run the `install_command` after `init_command`. And because of that dance, there are concerns about backwards compatibility which led to that branch become a long living branch. 

So I am curious about the tests you have done with this change. I tried to run acceptance tests of mixlib-install [here](https://github.com/chef/mixlib-install/tree/master/acceptance) but ran into some issues:

```
 >>>>>> Message: Could not load or activate winrm-fs. (winrm-fs is not part of the bundle. Add it to Gemfile.)
```

Probably not related. I will continue to get those tests to run.

**Comment by mwrock** [comment]
@sersut tk uses winrm-fs instead of the deprecated winrm-transport so you will just need to tweak your Gemfile accordingly.

I did notice the code you referred to in the provisioner base in your branch. I think given the changes over the last couple releases of tk, leaving that code alone should work. Test-kitchen since 1.5 grabs the script from mixlib-install and renders it to a file on the test instance.

**Comment by sersut** [comment]
Thanks for the info @mwrock. Fixing that I am now seeing the error here:

https://gist.github.com/sersut/113e36b2ec14440546f4

with 

https://github.com/chef/mixlib-install/blob/master/acceptance/current/.kitchen.yml

I think that is the core reason why we needed to do the dance in sersut/test-kitchen#1. 

The main difference is before mixlib-install, the command we run in the test instance downloads the install.sh and runs it like `sudo install.sh`. After mixlib-install the command we run in the test instance **is** the contents of install.sh. So running it with prepending `sudo -E` does not work.

**Comment by mwrock** [comment]
ah ok @sersut and I was testing with a windows test instance and therefore not running into this. I see it now on a linux instance. Will getr that working.

**Comment by mwrock** [comment]
so this is a bit hacky @sersut but its the simplest option I can think of without potentially breaking other TK provisioners.

**Comment by mwrock** [comment]
Actually I think this is better now. It writes to a file on non windows and then executes via sudo.

**Comment by mwrock** [comment]
Updated PR to reflect the just released mixlib-install 1.0.0 and removed the WIP marker. @sersut does the approach here for linux look fine to you now? Where we `cat` it to a file and run that as `sudo`?

**Comment by schisamo** [comment]
We should wait for the impending mixlib-install 1.0.1.

**Comment by mwrock** [comment]
I'll update the pr once that is released but still want to at least queue +1s. so this is ready to merge.

**Comment by mwrock** [comment]
this is updated to use at least mixlib-install 1.0.1 and I also noticed chef_base was not forwarding along `install_msi_url` making that impossible to override so I added that.

**Comment by mwrock** [comment]
note the appveyor break will be resolved with https://github.com/test-kitchen/test-kitchen/pull/981

**Comment by mwrock** [comment]
rebased with master to address appveyor and now aligning with mixlib-1.0.2

**Comment by patrick-wright** [comment]
:shipit:

**Comment by cheeseplus** [comment]
:shipit:

**Pull request merged**
