### PR TITLE
Use a relative name for the connection class.

### PR DESCRIPTION
**Pull request by coderanger**
This makes life easier for subclassing.

### CODE REVIEW

**Comment by metadave** [comment]
+1

**Comment by tyler-ball** [comment]
@coderanger How does this make it easier for subclassing?  Wouldn't you still need `< Kitchen::Transport::Ssh` on a subclass?

**Comment by coderanger** [comment]
@tyler-ball Right now you have to copy-pasta the whole method for any subclass. https://github.com/coderanger/kitchen-sync/blob/master/lib/kitchen/transport/sftp.rb#L29-L40

**Comment by coderanger** [comment]
The problem is you need two classes for a transport plugin and the glue between them is buried inside a method with other logic. The other fix for this would be to make a method that returns the connection class and use it in `create_new_connection`, so subclasses can override just that.

**Comment by tyler-ball** [comment]
@coderanger Gotcha - it makes it invoke the embedded `Connection` class rather than always invoking the `SSH::Connection` class.  Thanks for the explanation!

**Comment by coderanger** [comment]
That was the intent at least, relative constant lookups in Ruby are a weird minefield so I very well might have gotten that wrong :-)

**Comment by coderanger** [comment]
@cheeseplus At some point this got reverted. Can we revisit it?

**Pull request merged**
