### PR TITLE
Support IPv6 addresses for WinRM

### PR DESCRIPTION
**Pull request by jzinn**
Fixes test-kitchen/test-kitchen#1370

### CODE REVIEW

**Comment by cheeseplus** [comment]
This needs two minor style fixes to get the build green

```
Inspecting 133 files
.....................................................C...................................................................C...........
Offenses:
spec/kitchen/transport/winrm_spec.rb:72:37: C: Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
      transport[:scheme].must_equal 'http'
                                    ^^^^^^
lib/kitchen/transport/winrm.rb:394:17: C: Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
          path: '/wsman'
                ^^^^^^^^
```

**Comment by jzinn** [comment]
Updated

**Comment by cheeseplus** [comment]
My only concern here is that we're taking away an option and replacing it with a new one. I'm not sure how many people even knew about `endpoint_template` but I'd guess it's so few that we can probably get away with changing this w/o deprecation.

**Comment by jzinn** [comment]
I share the concern, and gave it some thought before submitting my PR.  I decided to submit a minimal change for clarity.  Adding deprecation code might not be too much work for someone more familiar with the code base and its deprecation process.

#### Why have `endpoint_template` in the first place?

I looked for motivation for making the endpoint more configurable.  I could not find any uses of `endpoint_template`.  The git history for `endpoint_template` seems to be lost.  A quick search of some other parts of Chef didn't turn up any similar URL template features.  A small sample of other Ruby WinRM code I looked at recently doesn't seem to offer more URL configuration.

I agree that it's probably a little-used feature.

#### If an alternative to `endpoint_template` is needed

If the endpoint does needs to be more configurable, then I would suggest adding more options for the parts of the URL that need it.  For instance, in addition to `scheme`, `host`, and `port`, we could add `path`, by adding a `default_config`:

```ruby
default_config :path, "/wsman"
```
and using it:
```ruby
endpoint = URI::Generic.build(
  scheme: data.fetch(:scheme),
  host: data.fetch(:hostname),
  port: data.fetch(:port),
  path: data.fetch(:path)
).to_s
```

**Comment by cheeseplus** [comment]
A thorough and complete answer 👍 

I think we're safe to change this for the better and enhance/fix later as needed.

**Pull request merged**
