### PR TITLE
Add hooks for instance cleanup before exit.

### PR DESCRIPTION
**Pull request by coderanger**
This fixes the zlib warning and can be extended in the future if needed.

### CODE REVIEW

**Comment by coderanger** [comment]
Ping @fnichol @tyler-ball, can someone push buttan on this and/or give me commit rights to do it myself? Would really like to see the zlib warning gone.

**Comment by coderanger** [comment]
@tyler-ball Can you please merge this before 1.5? Getting really sick of this warning.

**Comment by cheeseplus** [comment]
+1

**Comment by adamleff** [comment]
LGTM :+1:

**Pull request merged**
