### PR TITLE
Use command_prefix provided by Kitchen::Provisioner::Base in shell provisioner

### PR DESCRIPTION
**Pull request by pstengel**
Kitchen::Provisioner::Base provides a `:command_prefix` option for... prefixing commands. Use this in the shell provisioner so that we can do things like prefixing environment variables for use within the script.

### CODE REVIEW

**Comment by mwrock** [comment]
Here `prefix_command` is provided to `wrap_shell_code` while other provisioners have the opposite order such as `chef_zero` as an example:
```
      def run_command
        cmd = modern? ? local_mode_command : shim_command

        prefix_command(
          wrap_shell_code(
            [cmd, *chef_client_args].join(" ").
            tap { |str| str.insert(0, reload_ps1_path) if windows_os? }
          )
        )
      end
```
I'd consider doing the same here for the sake of consistency unless you have a specific reason to do otherwise.

**Comment by pstengel** [comment]
@mwrock 2759518

**Comment by mwrock** [comment]
just need to retrofit the test now :)

**Comment by pstengel** [comment]
@mwrock Whoops! 😄 6183127 should do it.

**Comment by mwrock** [comment]
:+1:

**Comment by smurawski** [comment]
:+1:

**Pull request merged**
