### PR TITLE
Shell Provisioner: make script executable

### LINKED ISSUE #931: Shell provisioner fails on Windows host to Linux guest
I have a mixed environment (Linux, Mac, Windows). I've been doing a lot of work with Test Kitchen on Mac and Linux. I'm getting a lot of my developer's on the Test Kitchen bandwagon.

Today I tried testing a basic kitchen config with virtualbox/vagrant/shell provisioner/bats test on a Windows machine to document it for my Windows developers.

The shell provisioner fails with "sudo: /tmp/kitchen/bootstrap.sh: command not found"
Windows7 / VirtualBox 5.0.14 / vagrant 1.8.1 / ruby 2.2.3 / Test Kitchen 1.5.0 running in a Git Bash shell (git version 2.7.0.windows.2). CentOS and Ubuntu LTS platforms from internally maintained vagrant box images. Same .kitchen.yml works fine on RHEL/CentOS & Mac OS X.

After doing some debugging, I've found the issue, but not sure what the right way to fix it is. The underlying issue is that the bootstrap script that is copied into the guest VM has 0644 permissions (no executable bit set).

The code path I'm looking at seems to start in lib/kitchen/provisioner/shell.rb. The host sets up a sandbox of files to copy over to the guest. Looking at the prepare_script() function, the bootstrap script gets copied to the host's sandbox dir and then FileUtils.chmod is called to make sure it is executable (0755). IIUC, FileUtils.chmod doesn't do anything on Windows (my host), so when the script is copied into the Linux guest, there is no Unix executable bit for Net::SCP (who is ultimately doing the copy) to send along with the file. (ls -l /tmp/kitchen/bootstrap.sh inside the guest confirms 0644 permissions).

After a failed converge, if I 'kitchen login' and then 'sudo chmod 755 /tmp/kitchen/bootstrap.sh' and rerun the converge, it succeeds (the scp overwrite the bootstrap, but doesn't change the file mode for what it copies over).

Maybe the chmod can be moved to be executed in the guest? Maybe the bootstrap can explicitly be called as "sh bootstrap.sh"? 

-Shawn

### PR DESCRIPTION
**Pull request by thewyzard44**
Resolves #931 and runs `chmod +x ...` in the guest, prior to executing the script

Based off of #442 but includes a guest OS check and only runs the command on *nix

### CODE REVIEW

**Comment by coderanger** [comment]
Hmm, I don't like this solution but I don't have a better idea :( Sigh windows.

**Comment by thewyzard44** [comment]
Yea, I had another thought...  load the script into memory and run the script directly through the transport...  I didn't like the loss of the shebang function, though :(

**Comment by thewyzard44** [comment]
and another thought...  the provisioner is calling common kitchen methods in order to generate an `sh -c scriptname.sh` command...  

what about either:
* add an option to Util::wrap_command to instead generate `sh scriptname.sh` avoiding the need for the execute bit
* or un-DRY this provisioner and replicate that function to do the same `sh scriptname.sh`

**Comment by cheeseplus** [comment]
I think I'm ok with pulling this in cause we don't really have anything better and the alternate methods seem to indicate we need a proper refactor of some things.

**Comment by coderanger** [comment]
Running the script via `sh ...` seems like a reasonable option, though the code would be just as gross, it's at least one fewer moving piece at run time.

**Comment by thewyzard44** [comment]
on 2nd thought...  running via `sh ...` kills the use of the shebang

**Comment by cheeseplus** [comment]
Let us know when you're happy with it and we can get it merged @thewyzard44

**Comment by thewyzard44** [comment]
yea i'm good with this as is.  Thank you!

**Comment by nimDevOps** [comment]
Hi,
This is my update of this issue with latest test-kitchen version 1.22.0. The issue is still there !!!
It looks like the chmod/prepare_command code does not work: I logged in into the node(centos7) and the file permissions on the /tmp/kitchen/bootstrap.sh are 0644. Here is my debug output:

$ kitchen converge --log-level=DEBUG NetCoreSDK-CentOS7
-----> Starting Kitchen (v1.22.0)
D      Berksfile found at D:/dev/chef/NetCoreSDK_Linux/Berksfile, loading Berkshelf
D      Berkshelf 6.3.1 library loaded
D      Berksfile found at D:/dev/chef/NetCoreSDK_Linux/Berksfile, loading Berkshelf
D      Berkshelf 6.3.1 previously loaded
-----> Converging <NetCoreSDK-CentOS7>...
       Preparing files for transfer
D      Creating local sandbox in C:/Users/<my_user>/AppData/Local/Temp/NetCoreSDK-CentOS7-sandbox-20180705-7948-mdgcug
       Preparing script
D      Using script from D:/dev/chef/NetCoreSDK_Linux/bootstrap.sh
D      [SSH] vagrant@10.132.254.224<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"vagrant", :paranoid=>false}> (sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E rm -rf /tmp/kitchen/data ; mkdir -p /tmp/kitchen
')
D      [SSH] opening connection to vagrant@10.132.254.224<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"vagrant", :paranoid=>false}>
       Transferring files to <NetCoreSDK-CentOS7>
D      TIMING: scp async upload (Kitchen::Transport::Ssh)
D      TIMING: scp async upload (Kitchen::Transport::Ssh) took (0m0.06s)
D      Transfer complete
D      Attempting to execute command - try 1 of 1.
D      [SSH] vagrant@10.132.254.224<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"vagrant", :paranoid=>false, :logger=>#<Logger:0x000000000877dcd0 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000000877dc58 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x000000000877dc08 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x000000000877dbb8>>>, :password_prompt=>#<Net::SSH::Prompt:0x000000000877db68>, :user=>"vagrant"}> (sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /tmp/kitchen/bootstrap.sh
')
       sudo: /tmp/kitchen/bootstrap.sh: command not found
D      Cleaning up local sandbox in C:/Users/<my_user>/AppData/Local/Temp/NetCoreSDK-CentOS7-sandbox-20180705-7948-mdgcug
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <NetCoreSDK-CentOS7>.  Please see .kitchen/logs/NetCoreSDK-CentOS7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Converge failed on instance <NetCoreSDK-CentOS7>.  Please see .kitchen/logs/NetCoreSDK-CentOS7.log for more details
D      ----------------------
D      ------Backtrace-------
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:183:in `report_errors'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:174:in `run_action'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command/action.rb:36:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command/action.rb:34:in `call'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/cli.rb:52:in `perform'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/bin/kitchen:13:in `block in <top (required)>'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/bin/kitchen:13:in `<top (required)>'
D      C:/opscode/chefdk/embedded/bin/kitchen:23:in `load'
D      C:/opscode/chefdk/embedded/bin/kitchen:23:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <NetCoreSDK-CentOS7>.  Please see .kitchen/logs/NetCoreSDK-CentOS7.log for more details
D      ----------------------
D      ------Backtrace-------
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/provisioner/base.rb:91:in `rescue in call'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/provisioner/base.rb:94:in `call'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:393:in `block in converge_action'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:498:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:497:in `action'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:389:in `converge_action'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:368:in `block in transition_to'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `each'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `transition_to'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:135:in `converge'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `public_send'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /tmp/kitchen/bootstrap.sh
']
D      ----------------------
D      ------Backtrace-------
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/provisioner/base.rb:91:in `rescue in call'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/provisioner/base.rb:94:in `call'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:393:in `block in converge_action'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:498:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:497:in `action'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:389:in `converge_action'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:368:in `block in transition_to'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `each'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `transition_to'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:135:in `converge'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `public_send'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/Users/<my_user>/AppData/Local/chefdk/gem/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----

**Comment by thewyzard44** [comment]
I've been trying to replicate this, but everything appears to be working.  Run `kitchen diagnose` and ensure that your os_type is picked up as unix.  And ensure that there is no `command:` entry in your kitchen.yml

**Comment by nimDevOps** [comment]
Here is 'kitchen diagnose' output:

---
timestamp: 2018-07-09 14:40:47 UTC
kitchen_version: 1.22.0
instances:
  NetCoreSDK-CentOS7:
    platform:
      os_type: linux
      shell_type: bourne
    state_file:
      hostname: 10.132.254.201
      last_action: create
      last_error: 
      vm_name: NetCoreSDK-CentOS7-7f2e6360
    driver:
      datacenter: <my_vcenter_datacenter>
      folder: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      name: vcenter
      poweron: true
      pre_create_command: 
      resource_pool: 
      targethost: 
      template: CentOS7_svn239.10
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      vcenter_disable_ssl_verify: true
      vcenter_host: <my_vcenter_host>
      vcenter_password: <my_vcenter_password>
      vcenter_username: <my_vcenter_username>
      vm_name: 
    provisioner:
      arguments: []
      command: 
      command_prefix: 
      data_path: 
      debug: 
      downloads: {}
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      max_retries: 1
      name: shell
      retry_on_exit_code: []
      root_path: "/tmp/kitchen"
      script: D:/dev/chef/NetCoreSDK_Linux/bootstrap.sh
      sudo: true
      sudo_command: sudo -E
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      elevated: true
      keepalive: true
      keepalive_interval: 60
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      password: vagrant
      port: 22
      ssh_gateway: 
      ssh_gateway_port: 22
      ssh_gateway_username: 
      ssh_http_proxy: 
      ssh_http_proxy_password: 
      ssh_http_proxy_port: 
      ssh_http_proxy_user: 
      ssh_key: 
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      username: vagrant
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      debug: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: NetCoreSDK
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      version: busser
  NetCoreSDK-Ubuntu16:
    platform:
      os_type: linux
      shell_type: bourne
    state_file: {}
    driver:
      datacenter: <my_vcenter_datacenter>
      folder: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      name: vcenter
      poweron: true
      pre_create_command: 
      resource_pool: 
      targethost: 
      template: Xenial_svn239.7
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      vcenter_disable_ssl_verify: true
      vcenter_host: <my_vcenter_host>
      vcenter_password: <my_vcenter_password>
      vcenter_username: <my_vcenter_username>
      vm_name: 
    provisioner:
      arguments: []
      command: 
      command_prefix: 
      data_path: 
      debug: 
      downloads: {}
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      max_retries: 1
      name: shell
      retry_on_exit_code: []
      root_path: "/tmp/kitchen"
      script: D:/dev/chef/NetCoreSDK_Linux/bootstrap.sh
      sudo: true
      sudo_command: sudo -E
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      elevated: true
      keepalive: true
      keepalive_interval: 60
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      password: vagrant
      port: 22
      ssh_gateway: 
      ssh_gateway_port: 22
      ssh_gateway_username: 
      ssh_http_proxy: 
      ssh_http_proxy_password: 
      ssh_http_proxy_port: 
      ssh_http_proxy_user: 
      ssh_key: 
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      username: vagrant
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      debug: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: NetCoreSDK
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      version: busser
  NetCoreSDKAgent-CentOS7:
    platform:
      os_type: linux
      shell_type: bourne
    state_file: {}
    driver:
      datacenter: <my_vcenter_datacenter>
      folder: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      name: vcenter
      poweron: true
      pre_create_command: 
      resource_pool: 
      targethost: 
      template: CentOS7_svn239.10
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      vcenter_disable_ssl_verify: true
      vcenter_host: <my_vcenter_host>
      vcenter_password: <my_vcenter_password>
      vcenter_username: <my_vcenter_username>
      vm_name: 
    provisioner:
      always_update_cookbooks: false
      architecture: 
      attributes:
        ant:
          install_method: source
          version: 1.10.3
        chef-teamcity:
          agent:
            name: NetCoreSDKAgent
            server_uri: http://10.132.253.24
            env_properties:
              DOTNET_CLI_TELEMETRY_OPTOUT: '1'
            opt_properties:
              teamcity.agent.cpuBenchmark.enabled: 'False'
      channel: :stable
      checksum: 
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options: 
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host: 
      chef_zero_port: 8889
      client_rb: {}
      clients_path: 
      command_prefix: 
      config_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: 
      data_path: 
      debug: 
      deprecations_as_errors: false
      download_url: 
      downloads: {}
      encrypted_data_bag_secret_key_path: 
      enforce_idempotency: false
      environments_path: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      install_strategy: once
      json_attributes: true
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_file: 
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_zero
      named_run_list: {}
      nodes_path: 
      platform: 
      platform_version: 
      policyfile: 
      policyfile_path: 
      product_name: 
      product_version: :latest
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code:
      - 35
      - 213
      roles_path: 
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[git::default]
      - recipe[subversion::default]
      - recipe[java_se::default]
      - recipe[ant::default]
      - recipe[chef-teamcity::agent]
      sudo: true
      sudo_command: sudo -E
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      elevated: true
      keepalive: true
      keepalive_interval: 60
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      password: vagrant
      port: 22
      ssh_gateway: 
      ssh_gateway_port: 22
      ssh_gateway_username: 
      ssh_http_proxy: 
      ssh_http_proxy_password: 
      ssh_http_proxy_port: 
      ssh_http_proxy_user: 
      ssh_key: 
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      username: vagrant
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      debug: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: NetCoreSDKAgent
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      version: busser
  NetCoreSDKAgent-Ubuntu16:
    platform:
      os_type: linux
      shell_type: bourne
    state_file: {}
    driver:
      datacenter: <my_vcenter_datacenter>
      folder: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      name: vcenter
      poweron: true
      pre_create_command: 
      resource_pool: 
      targethost: 
      template: Xenial_svn239.7
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      vcenter_disable_ssl_verify: true
      vcenter_host: <my_vcenter_host>
      vcenter_password: <my_vcenter_password>
      vcenter_username: <my_vcenter_username>
      vm_name: 
    provisioner:
      always_update_cookbooks: false
      architecture: 
      attributes:
        ant:
          install_method: source
          version: 1.10.3
        chef-teamcity:
          agent:
            name: NetCoreSDKAgent
            server_uri: http://10.132.253.24
            env_properties:
              DOTNET_CLI_TELEMETRY_OPTOUT: '1'
            opt_properties:
              teamcity.agent.cpuBenchmark.enabled: 'False'
      channel: :stable
      checksum: 
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options: 
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host: 
      chef_zero_port: 8889
      client_rb: {}
      clients_path: 
      command_prefix: 
      config_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: 
      data_path: 
      debug: 
      deprecations_as_errors: false
      download_url: 
      downloads: {}
      encrypted_data_bag_secret_key_path: 
      enforce_idempotency: false
      environments_path: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      install_strategy: once
      json_attributes: true
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_file: 
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_zero
      named_run_list: {}
      nodes_path: 
      platform: 
      platform_version: 
      policyfile: 
      policyfile_path: 
      product_name: 
      product_version: :latest
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code:
      - 35
      - 213
      roles_path: 
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[git::default]
      - recipe[subversion::default]
      - recipe[java_se::default]
      - recipe[ant::default]
      - recipe[chef-teamcity::agent]
      sudo: true
      sudo_command: sudo -E
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      elevated: true
      keepalive: true
      keepalive_interval: 60
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      password: vagrant
      port: 22
      ssh_gateway: 
      ssh_gateway_port: 22
      ssh_gateway_username: 
      ssh_http_proxy: 
      ssh_http_proxy_password: 
      ssh_http_proxy_port: 
      ssh_http_proxy_user: 
      ssh_key: 
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      username: vagrant
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      debug: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: D:/dev/chef/NetCoreSDK_Linux
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: NetCoreSDKAgent
      test_base_path: D:/dev/chef/NetCoreSDK_Linux/test/integration
      version: busser

**Comment by nimDevOps** [comment]
Just FYI, the fix I'm using to workaround the issue has literally 4 lines of code:
1. clone sudo(script) function in base.rb and create sudo_shell(script) function:
    def sudo_shell(script)
        "#{sudo_command} /bin/sh #{script}".lstrip
     end
2. Modify line 114 in shell.rb to use this new function:
    code = powershell_shell? ? %{& "#{script}"} : sudo_shell(script)

That's it. All other places will use previous implementation of sudo(script) function in commands etc.

About 'shebang' concerns:
 - First of all the name of the script is 'bootstrap.sh' ( not bootstrap.bash nor bootstrap.ksh), which usually means that this is /bin/sh compatible script.
- Second, we may create 'default_shell' variable with value '/bin/sh' and allow user to pick another default_shell by user's choice to match with first line of bootstrap.sh.

**Pull request merged**
