### PR TITLE
re-adds PATH

### PR DESCRIPTION
**Pull request by curiositycasualty**
??

### CODE REVIEW

**Comment by scotthain** [comment]
@fnichol Can we add this to the 'existing' path and add /usr/sfw/bin to the tacked-on path?

**Comment by fnichol** [comment]
Seems like the absolutely perfect PR number

**Comment by fnichol** [comment]
@scotthain I'll see what that looks like.

@curiositycasualty Were you able to narrow down what required these lines? We weren't able to determine why they were there in the first place…

**Comment by fnichol** [comment]
Done!

**Pull request merged**
