### PR TITLE
include hidden files when copying over from sandbox to target

### PR DESCRIPTION
**Pull request by hslee16**
Currently, the upload from sandbox_dir doesn't include hidden files (.e.g [.filename])

This PR aims to include hidden files.

### CODE REVIEW

**Comment by cheeseplus** [comment]
My initial feeling is that this behaviour should be something optional and not the default.

**Comment by coderanger** [comment]
:-1: I don't think this is a good idea overall, and this patch doesn't implement the feature correctly anyway.

**Comment by coderanger** [comment]
(stuff like `.~whatever` wouldn't be transferred, should use `Dir.entries` or similar to actually get all files if that's what we want to do)

**Comment by cheeseplus** [comment]
For the reasons above as well as not wanting to make this the default behaviour I'm going to close the PR. That said we have some other PRs and Issues related to issues around including/excluding files that will likely address this concern.

Thanks again for the PR!

**Comment by hslee16** [comment]
@cheeseplus @coderanger thanks for the reply!

**Pull request closed without merging**
