### PR TITLE
Add legacy_mode argument for chef_solo provisioner

### PR DESCRIPTION
**Pull request by SaltwaterC**
Proposed fix for #1070.

### CODE REVIEW

**Comment by mwrock** [comment]
This generally looks good but I'd love to see a test in https://github.com/test-kitchen/test-kitchen/blob/master/spec/kitchen/provisioner/chef_solo_spec.rb

**Comment by SaltwaterC** [comment]
Test pushed to my feature branch. Rewritten history to have only one commit. The CI services seem to accept it.

**Comment by thommay** [comment]
:+1: LGTM

**Comment by mwrock** [comment]
:+1:

**Pull request merged**
